### ISSUE TITLE
dgram is deprecated

### ISSUE THREAD

**Issue by DougAnderson444** [mafintosh/dht-rpc#20]
https://www.npmjs.com/package/dgram

But it's used in dht-rpc

**Comment by mafintosh** [comment]
dgram is a core api provided by node.js

https://nodejs.org/dist/latest-v12.x/docs/api/dgram.html

**Comment by DougAnderson444** [comment]
Hmm, ok. The reason I noted this was I was getting an error when trying to run hyperswarm about not being able to resolve dgram.
```
Module not found: Can't resolve 'dgram' in '\node_modules\dht-rpc'
```
I saw it's [require'd in dht-rpc](https://github.com/mafintosh/dht-rpc/blob/81cf7724d1a56df21c03d408e3f8303b58abbdc0/index.js#L3). 

Since it's part of Node, does this have to be changed?

**Comment by DougAnderson444** [comment]
Ah, wait, maybe it's only for v12 (and I'm running node 10)

**Comment by mafintosh** [comment]
It’s been in Node since the beginning.
What platform are you on?

**Comment by DougAnderson444** [comment]
Windows 8
