### ISSUE TITLE
Add ability to persist and load nodes

### ISSUE THREAD

**Issue by aureooms** [mafintosh/dht-rpc#21]
Continuing https://github.com/hyperswarm/dht/issues/4.

**Comment by aureooms** [comment]
Something like the following:

```js
class DHT extends EventEmitter {

  ...

  toJSON () {
    return {
      nodes: this.nodes.toArray(),
    }
  }

  addNodes (nodes) {
    for (const node of nodes) {
      const { id , token , to } = node
      const peer = {
        host: node.host,
        port: node.port,
      }
      this._addNode(id, peer, token, to)
    }
  }

}

```

**Comment by mafintosh** [comment]
Yep! I wouldn't call it toJSON though as the ids are binary. Just toArray() or toNodesArray() is fine

**Comment by aureooms** [comment]
What about the `next` and `prev` properties leaking from the `tos` should we throw them away?
Same for `tick`.
We could still have a convenience function to output some JSON. Stringify the ids?

**Comment by mafintosh** [comment]
Good idea stripping the private info. A map of that array to { id, port, ip, referrer: { ip, port, id } } should be enough.

I'm soft -1 on stringify'ing the ids. I think that is the responsibility of whoever is serialising. Alternatively addNodes should deserialise them from hex if they are strings.

**Comment by aureooms** [comment]
What should be in the referrer ?

```js
class DHT extends EventEmitter {

  ...

  getNodes () {
    return this.nodes.toArray().map(
      ({id, host, port, roundtripToken, to}) => ({
        id,
        host,
        port,
        referrer: { ? }
      })
    )
  }

  addNodes (nodes) {
    for (const node of nodes) {
      const { id , token , to } = node
      const peer = { host , port } = node
      this._addNode(id, peer, token, to)
    }
  }


}

```

**Comment by mafintosh** [comment]
@aureooms node.referrer is set on the node. not all nodes have this

**Comment by aureooms** [comment]
> @aureooms node.referrer is set on the node. not all nodes have this

@mafintosh I see.

**Comment by aureooms** [comment]
What should we do with `referrer` in `addNodes`? Should we even care about `token` and `to` being given?

```js
class DHT extends EventEmitter {

  ...

  getNodes () {
    return this.nodes.toArray().map(
      ({id, host, port, referrer }) => ({
        id,
        host,
        port,
        referrer: referrer === null ? null : {
          id: referrer.id,
          host: referrer.host,
          port: referrer.port,
        }
      })
    )
  }

  addNodes (nodes) {
    for (const node of nodes) {
      const { id , token , to } = node
      const peer = { host , port } = node
      this._addNode(id, peer, token, to)
    }
  }

}

```

**Comment by mafintosh** [comment]
We don't care about token/to.

Actually we don't persist the referrer in the nodes table, so disregard that for now.

**Comment by aureooms** [comment]
Final iteration?

```js
class DHT extends EventEmitter {

  ...

  getNodes () {
    return this.nodes.toArray().map(
      ({id, host, port, referrer }) => ({
        id,
        host,
        port,
        referrer: referrer === null ? null : {
          id: referrer.id,
          host: referrer.host,
          port: referrer.port,
        }
      })
    )
  }

  addNodes (nodes) {
    for (const { id , host , port } of nodes) {
      this._addNode(id, { host , port })
    }
  }

}

```

**Comment by mafintosh** [comment]
just skip the referrer on export for now, other than that looks good to me. can you open a PR?

**Comment by aureooms** [comment]
Yes!

**Comment by aureooms** [comment]
PR at https://github.com/mafintosh/dht-rpc/pull/22. I added some tests. Could not get rid of the `setTimeout` for some reason. Had to trigger some command on `a` for it to add `b` as a node.
