### ISSUE TITLE
seeking explanation of workings

### ISSUE THREAD

**Issue by NHQ** [mafintosh/dht-rpc#7]
I have a couple Q about how this works, which a couple hours study into source did not elucidate. 

1. When a node queries the DHT (eg. a new ephemeral node queries as hash dictionary command), after bootstrapping, does it then ask around non-ephemeral nodes if they can answer the query, or what happens?

2.  When an update is performed, do all nodes in the DHT eventually receive that same command update, or only a subset of the nodes?

3.  What is a good entry point for hacking access privileges into this module?

TIA

**Comment by KrishnaPG** [comment]
Another important question, along with the above listed ones is: how to prevent nodes "lying"?

For example, how can one ensure that nodes 

1. do not give incorrect values for a given key, 
2. do not say "I do not have the key", when they indeed have the key
3. do not flood the system with too many garbage key-value pairs (that have no real use, except for just flooding the system and DOS)

**Comment by mafintosh** [comment]
The DHT traversal algo does not guarantee anything in regards to security, that's up to you, the implementer, to build. For example, use signed keys etc. It also provides a scalable algorithm for running large scale DHT networks where you can efficiently find peers. Same goes for DOS etc

**Comment by mafintosh** [comment]
To answer the original Q which I messed.

1. Only non ephemeral nodes are queried.
2. Only a subset is reached (log(n))
3. You wanna use some crypto. See hyperswarm/dht for how to impl a secure kv store as an example.
